const FETCH_PRODUCTS = 'SHOPPING_CART/FETCH_PRODUCTS';
const SAVE_PRODUCTS = 'SHOPPING_CART/SAVE_PRODUCTS';
const DELETE_PRODUCT = 'SHOPPING_CART/DELETE_PRODUCT';
const UPDATE_PRODUCT_QUANTITY = 'SHOPPING_CART/UPDATE_PRODUCT_QUANTITY';
const VALIDATE_PINCODE = 'SHOPPING_CART/VALIDATE_PINCODE';
const UPDATE_PINCODE = 'SHOPPING_CART/UPDATE_PINCODE';

export {
    FETCH_PRODUCTS,
    SAVE_PRODUCTS,
    DELETE_PRODUCT,
    UPDATE_PRODUCT_QUANTITY,
    VALIDATE_PINCODE,
    UPDATE_PINCODE,
};
